baseURL: "https://officegeek.online"
languageCode: "en-us"
title: "OfficeGeek"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 12

outputFormats:
  search:
    baseName: search
    isPlainText: true
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - search

taxonomies:
  categories: 'categories'
  kategorier: 'kategorier'
permalinks:
  kategorier: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
  description: "Online courses"
  logo: "/images/logo.svg"
  logo_footer: "/images/logo.svg"
  footer_text: "Since 1995, I have taught companies and course providers. A lot of satisfied customers over the years"
  contact_text: "If you have any questions or anything else please contact me"
  copyright: "Copyright © 2022"
  author: "OfficeGeek"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "OfficeGeek"
  twitter: "#"
  email: tue@officegeek.online
  phone: +45 2065 7117
  address: Sprydet 19, 3070 Snekkersten, Denmark


  social:
    facebook: "#"
    youtube: "#"
    linkedin: "#"

  navbar:
  - name: Courses
    url: "/kurser/"
  - name: Webinar
    url: "/webinar/"
  - name: One to One
    url: "/en-til-en/"
  - name: Questions
    url: "/sporgsmal/"
  - name: Blog
    url: "/blog/"
  - name: About
    url: "/om/"
  - name: Contact
    url: "/kontakt/"

  footer_1:
    heading: Services
    links: 
    - name: Courses
      url: "/kurser/"
    - name: Webinar
      url: "/webinar/"
    - name: One to One
      url: "/en-til-en/"
    - name: Questions
      url: "/sporgsmal/"

  footer_2:
    heading: Links
    links: 
    - name: Blog
      url: "/blog/"
    - name: About
      url: "/om/"
    - name: Contact
      url: "/kontakt/"
    - name: Terms
      url: "/terms/"
